### PR TITLE
new collection support

### PR DESCRIPTION
**Pull request by ableeb**
Hi I added support for plone.app.collections. Please let me know if you see anything missing. Thanks

### CODE REVIEW

**Comment by mishunov** [comment]
Hei, @ableeb. Thanks for the Pull Request. Do you mind writing tests for your changes?

Hi mishunov - Certainly! I'll do that in the next day or so.

**Comment by mishunov** [comment]
Hi @ableeb. I have made quite a few commits to the branch as you can see. I have also added tests for the new-style collection. The only thing that is missing is the tests for the carousel portlet with the new-style collections. Could you please write a couple? Once we have it in place, I will merge the branch to master if you say that the branch works sane. After that we might bake a new release.

Hi @mishunov - Thanks for adding the tests. I'll add the tests for the portlet done this weekend.

**Comment by ableeb** [comment]
Hi @mishunov - I added  a couple of tests for new style collections in the portlet, specifically to make sure that the collection added to the portlet has the same results as a collection. The other test ensures that the correct edit link is presented.

I think this branch is ready to merge into master. Let me know what you think.

Thanks

**Comment by mishunov** [comment]
Thanks a lot @ableeb. Yes, I agree, we are ready to merge the branch and, [ bang-bang ] cut a new release out of this beast ;)

**Comment by mishunov** [comment]
@ableeb I have released version 1.5 with this branch in. Thanks for your time and effort!

**Pull request merged**
